// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKUyV6lCMxdC6m3u0nFn1hXbUA4MrTgzk',
    appId: '1:18368839397:web:b25263ce60f53b93e75e0c',
    messagingSenderId: '18368839397',
    projectId: 'babyshop-aefcd',
    authDomain: 'babyshop-aefcd.firebaseapp.com',
    storageBucket: 'babyshop-aefcd.appspot.com',
    measurementId: 'G-SSCBWWL7SB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9rcmpQKVF2hjeNsySCMDKOu9At3OqxMA',
    appId: '1:18368839397:android:3896898f84f017f6e75e0c',
    messagingSenderId: '18368839397',
    projectId: 'babyshop-aefcd',
    storageBucket: 'babyshop-aefcd.appspot.com',
  );
}
